### ISSUE TITLE
Water balance error when running Noah-MP with MMF groundwater scheme

### ISSUE THREAD

**Issue by bieri2** [NCAR/hrldas#29] opened 2023-01-25 11:03 UTC
Hello! 

I am running HRLDAS for a region in South America (see grey outline in the figure below). The domain is 129 x 129 grid cells at 4 km resolution.
<img width="448" alt="image" src="https://user-images.githubusercontent.com/60154150/214382076-25cbbf18-c2b9-4dde-b967-a471a67ad544.png">
I have no problem running the model for this domain using RUN_OPT=3 (free drainage). However, when I use RUN_OPT=5 (MMF groundwater scheme), I get a water balance error (see screenshot below; the full log file is here: [hrldas_log.txt](https://github.com/NCAR/hrldas/files/10493224/hrldas_log.txt)). 

<img width="742" alt="Screen Shot 2023-01-24 at 7 56 44 PM" src="https://user-images.githubusercontent.com/60154150/214386712-cafea7b2-1334-4a92-809b-b589092638a4.png">

I'm struggling to find the source of the error...there doesn't seem to be anything obviously wrong with the MMF input variables in the wrfinput file. The magnitude and location of the error makes me think there could be an issue with variable initialization, as I see that in [module_NoahMP_hrldas_driver.F](https://github.com/NCAR/hrldas/blob/master/hrldas/IO_code/module_NoahMP_hrldas_driver.F) variables are set to a large fill value.

In the zip folder below I'm including the namelist file & wrfinput file (my HRLDAS setup file) that I'm using, and a few forcing files. These can be used to recreate the error.

[HRLDAS_data.zip](https://github.com/NCAR/hrldas/files/10498260/HRLDAS_data.zip)

Is this a bug or is there an issue with my setup of the model? Let me know if there's any other information I can provide.

Thank you!

**Comment by cenlinhe** [comment] 2023-02-19 05:34
Hi there, looks like some variables have missing values in your run. Your namelist looks good. Did you use serial run (single core) or mpi parallel run? Currently, there are some issues with the mpi run for MMF scheme in HRLDAS. Could you please try using serial run to see if it solves the problem.

**Comment by cenlinhe** [comment] 2023-02-19 06:27
@prasanthvkrishna Do you have any suggestions?

**Comment by bieri2** [comment] 2023-02-23 17:46
Hello! 

I used a serial run and I'm running the model on Cheyenne. When I ran ./configure to create the user_build_options file, I chose option 3 (Linux ifort compiler serial).

**Comment by cenlinhe** [comment] 2023-02-23 17:57
It may be the something wrong regarding initial condition. We also saw this in our recent testing. We are trying to solve this problem and will let you know if we have a solution.

**Comment by cenlinhe** [comment] 2023-02-23 23:28
@bieri2 The issue is caused by a bug in groundwater_init. Please change "ide" and "jde" to "ide+1" and "jde+1" in this line when calling the groundwater_init: https://github.com/NCAR/hrldas/blob/master/hrldas/IO_code/module_NoahMP_hrldas_driver.F#L2330

**Comment by bieri2** [comment] 2023-02-24 12:00
That fixed the issue. Thank you!

**Comment by cenlinhe** [comment] 2023-02-24 15:51
I am closing this issue, since the bug has been fixed in the latest HRLDAS github code

**Closed as completed** 2023-02-24 15:51 UTC
